# Generated by Django 2.2.5 on 2019-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comms',
            name='location',
            field=models.CharField(choices=[('comms', 'comms'), ('scrape', 'scrape'), ('landing', 'landing')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
