# Generated by Django 2.2.5 on 2019-09-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0002_comms_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comms',
            old_name='location',
            new_name='site_location',
        ),
    ]
