# Generated by Django 2.2.5 on 2019-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0003_auto_20190906_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='comms',
            name='meta',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
