# Generated by Django 2.2.5 on 2019-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0004_comms_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comms',
            name='meta',
        ),
    ]
