# Generated by Django 2.2.5 on 2019-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0005_remove_comms_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comms',
            name='site_location',
            field=models.CharField(choices=[('comms', 'comms'), ('scrape', 'scrape'), ('landing', 'landing')], max_length=120),
        ),
    ]
