# Generated by Django 2.2.5 on 2019-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelp',
            name='page_amount',
            field=models.IntegerField(blank=True, default=1, max_length=2, null=True),
        ),
    ]
