# Generated by Django 2.2.5 on 2019-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_yelp_page_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='page_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
