# Generated by Django 2.2.5 on 2019-09-24 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrape', '0004_auto_20190918_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yelp',
            new_name='Collect',
        ),
    ]
