# Generated by Django 2.2.5 on 2019-09-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20190924_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='YelpResults',
        ),
    ]
