# Generated by Django 2.2.5 on 2019-09-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20190924_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpresults',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yelp_reviews', to='scrape.Collect'),
        ),
        migrations.CreateModel(
            name='GlassdoorResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120)),
                ('rating', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glassdoor_reviews', to='scrape.Collect')),
            ],
        ),
    ]
