# Generated by Django 2.2.5 on 2019-10-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20190924_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120)),
                ('rating', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scrape.Collect')),
            ],
        ),
        migrations.RemoveField(
            model_name='yelpresults',
            name='business',
        ),
        migrations.DeleteModel(
            name='GlassdoorResults',
        ),
        migrations.DeleteModel(
            name='YelpResults',
        ),
    ]
