# Generated by Django 2.2.5 on 2019-10-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_auto_20191003_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='business',
            new_name='collection_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='business',
            new_name='collection_id',
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('collection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='scrape.Collect')),
            ],
        ),
    ]
