# Generated by Django 2.2.5 on 2019-10-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_auto_20191004_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='timestamp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
