# Generated by Django 2.2.5 on 2019-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0012_results_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indeedresults',
            old_name='author',
            new_name='current_employee',
        ),
        migrations.RemoveField(
            model_name='results',
            name='current_employee',
        ),
        migrations.RemoveField(
            model_name='results',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='results',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='results',
            name='location_state',
        ),
        migrations.AddField(
            model_name='indeedresults',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indeedresults',
            name='location_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indeedresults',
            name='location_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
