# Generated by Django 2.2.5 on 2019-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0013_auto_20191007_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='site',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
